- name: install and start nginx service
  hosts: frontend
  tasks:
  - name: install nginx
    ansible.builtin.package:
      name: nginx
      state: present
  - name: start nginx service
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes