- name: task level variable
  hosts: local
  connection: local
  vars:
    COURSE: "ANSIBLE"
    DURATION: "10 HR"
  tasks:
    - name: print the course and the duration
      ansible.builtin.debug:
        msg: "Course is {{ COURSE }} and duration is {{ DURATION }} "
    - name : print the course and the duration with task level variable
      vars:
        COURSE: "task level ANSIBLE"
        DURATION: "2 HR"
      ansible.builtin.debug:
        msg: "Course is {{ COURSE }} and duration is {{ DURATION }} "
      

