- name: print variable from inventory
  hosts: frontend
  tasks:
  - name : print about the subject learnt
    ansible.builtin.debug:
      msg: "SKILLS learnt are {{ SUBJECT1 }}, {{ SUBJECT2 }} and {{ SUBJECT3 }}"
  - name : print Greeting
    ansible.builtin.debug:
      msg: "{{ GREETING }}"
