- name: print variable from inventory
  hosts: local
  connection: local
  tasks:
  - name : print about the subject learnt
    ansible.builtin.debug:
      msg: "SKILLS learnt are {{ SUBJECT1 }}, {{ SUBJECT2 }} and {{ SUBJECT3 }}"
