- name: ansible datatypes
  hosts: local
  connection: local
  vars:
    DURATION: 100
    LEARNER_NAME: "MAHA"
    ISLIVE: true
    TOOLS:
    - linux
    - shell
    - ansible
    SKILLS:
      CI: jekins
      SCRIPTING: "shell, ansible , linux"
          

  tasks:
  - name: print datatypes
    ansible.builtin.debug:
      msg: " DURATION: {{ DURATION }}  , LEARNER_NAME:{{ LEARNER_NAME }} ISLIVE:{{ ISLIVE }}"
   
  - name: print list
    ansible.builtin.debug:
      msg: " TOOLS: {{ TOOLS }}  "

                                      
  - name: print dictionary
    ansible.builtin.debug:
      msg: " SKILLS: {{ SKILLS }}  "




